name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [debian, fedora, ubuntu]

    name: Linux
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker build -f Dockerfile.${{ matrix.flavor }} -t profanity .
          docker run profanity ./ci-build.sh

#  macos:
#    runs-on: macos-latest
#    name: macOS
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run brew bundle
#        run: brew bundle
#      - name: Run tests
#        env:
#          # Ensure that "keg-only" Homebrew versions are used.
#          PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"
#        run: ./ci-build.sh

  code-style:
    runs-on: ubuntu-20.04
    name: Check coding style
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends autoconf autoconf-archive automake expect gcc git libcmocka-dev libcurl3-dev libgcrypt-dev libglib2.0-dev libgpgme11-dev libgtk2.0-dev libmicrohttpd-dev libncursesw5-dev libnotify-dev libotr5-dev libreadline-dev libsignal-protocol-c-dev libssl-dev libtool libxss-dev make pkg-config python3-dev python-dev-is-python3 libsqlite3-dev
      - name: Install libstrophe
        run: |
          git clone https://github.com/strophe/libstrophe ../libstrophe
          cd ../libstrophe && ./bootstrap.sh && ./configure && make -j$(nproc) && sudo make install
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure
      - name: Check style
        run: |
          make format
          git diff --exit-code
